				/* ----------------- CRIANDO A TABELA CLIENTE ----------------- */

CREATE TABLE CLIENTE(
		IDCLIENTE INT PRIMARY KEY IDENTITY,
		NOME VARCHAR(100) NOT NULL,
		EMAIL VARCHAR(255) NOT NULL UNIQUE,
		SENHA VARCHAR(32) NOT NULL,
		DATA_INCLUSAO DATETIME,
		DATA_ALTERACAO DATETIME
	);

			/* ----------------- ALGUNS DADOS DA TABELA CLIENTE ----------------- */

INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO) 
VALUES('Joao Cardoso Barbosa', 'joao_card47@gmail.com', 'uTj&2aNwBB2DMvD+*-Y4S5=zw_hwx', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO) 
VALUES('Rafael Araujo Sousa', 'rafael_sousa14@outlook.com', 'W68^rf7-pZyXqG6', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Emily Ribeiro Ferreira', 'emilyfe12@gmail.com', '^H3&Z#2P6g-GqYwk=j', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Antônio Pinto Cunha', 'antonio_pc90@outlook.com', 'JSv*gL-a99W', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Felipe Soares José Gonçalves', 'felipe_soares11@gmail.com', 'gO(H\$%z7A$PjO3<A95Crv|am', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO) 
VALUES('Tiago Barros Araujo', 'tiago984@gmail.com', 'e()j#wucauN;:gs4;Qp* 9J)9A0n(*', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Diogo Alves Gomes', 'diogoAlves1991@outlook.com', 'k+,X\m)d', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO) 
VALUES('Martim Lima Pinto', 'martim99@gmail.com', 't03jyAE?"hmTVmh(', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO) 
VALUES('Melissa Fernandes Azevedo', 'melissa_azevedo11@gmail.com', 'kr,FcAWQP~m_C]', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Otávio Gomes Cavalcanti', 'otavio_calva53@outlook.com', 'dQwgJ:>B.lNT;+73J@2<bd', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO) 
VALUES('Estevan Correia Costa', 'estevan_costa33@gmail.com', 'jDX{Yg1]#p7M@xlJtNGKJRy{e', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO) 
VALUES('Daniel Carvalho Cavalcanti', 'dani_carvalho65@gmail.com', 'u.c6qXgRb9idkGaaDY-7r@"', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Manuela Pereira Oliveira', 'manu_oliveira153@gmail.com', 'jzqsD-|l4:]e', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Tânia Cunha Castro', 'tania_castro88@outlook.com', 'd?G5cjg90j0@+-L', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Vitoria Correia Rodrigues', 'vitoria_rodrigues134@outlook.com', 'ys%JqaU&Mg.sJ;cn4nPEgU57w', GETDATE());
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
VALUES('Clara Lima Pereira', 'clara_lima65@outlook.com', 'uXW_Z#+2W4E#tzK-k!', GETDATE());


			/* ----------------- CRIANDO A TABELA ENDEREÇO ----------------- */


CREATE TABLE ENDERECO(
		IDENDERECO INT PRIMARY KEY IDENTITY,
		CEP VARCHAR(10) NOT NULL,
		COMPLEMENTO VARCHAR(255),
		BAIRRO VARCHAR(255) NOT NULL,
		CIDADE VARCHAR(255) NOT NULL,
		ESTADO CHAR(2) NOT NULL,
		DATA_INCLUSAO DATETIME,
		DATA_ALTERACAO DATETIME,
		ID_CLIENTE INT

-- CHAVE ESTRANGEIRA

		FOREIGN KEY (ID_CLIENTE)
		REFERENCES CLIENTE(IDCLIENTE)
	);


			/* ----------------- ALGUNS DADOS DA TABELA ENDEREÇO ----------------- */

INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(4, '29193-042', 'Rua Belmiro Segatto', 'Jequitibá' , 'Aracruz', 'ES', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(1,'79094-020', 'Rua Visconde', 'Jardim Tijuca' , 'Campo Grande', 'MS', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO)
VALUES(10, '37026-036', 'Avenida Otávio Marques de Paiva', 'Novo Horizonte' , 'Varginha', 'MG', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO)
VALUES(3, '49087-830', 'Rua João Figueiredo Neto', 'Santos Dumont' , 'Aracaju', 'SE', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(6, '97507-542', 'Rua Guatambu', 'Vila Júlia' , 'Uruguaiana', 'RS', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(16, '71555-205', 'Quadra Quadra 6 Conjunto E', 'Varjão' , 'Brasília', 'DF', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(4, '89211-488', 'Rua Paraguaçu', 'Floresta' , 'Joinville', 'SC', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(2, '69104-710', 'Rua Andorinha', 'Da Paz' , 'Itacoatiara', 'AM', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(12, '74692-375', 'Rua Pequi', 'Sítios de Recreio Caraíbas' , 'Goiânia', 'GO', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(5, '04045-901', 'Avenida Jabaquara 1761', 'Mirandópolis' , 'São Paulo', 'SP', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(8, '58406-830', 'Rua Professor Iraildo Gomes de Abreu, Casa 88', 'Nova Brasília' , 'Campina Grande', 'PB', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(13, '99709-100', 'Rua Luigi Tormen', 'Aeroporto' , 'Erechim', 'RS', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO)
VALUES(5, '06768-100', 'Rodovia Regis Bittencourt', 'Jardim Monte Alegre' , 'Taboão da Serra', 'SP', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(12, '75802-205', 'Rua 109-A', 'Setor Industrial' , 'Jataí', 'GO', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(11, '59114-680', 'Rua Jardim Esperança', 'Nossa Senhora da Apresentação' , 'Natal', 'RN', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO)
VALUES(10, '69905-064', 'Travessa Benjamim Constant', 'Cerâmica' , 'Rio Branco', 'AC', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(14, '77025-446', 'Quadra ARSO 151 QI 23', 'Plano Diretor Sul' , 'Palmas', 'TO', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(9, '69318-065', 'Rua CC-14', 'Senador Hélio Campos' , 'Boa Vista', 'RR', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(6, '99711-144', 'Rua Vitorio Fasolo', 'Koller' , 'Erechim', 'RS', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(15, '60170-220', 'Rua Júlio Ibiapina', 'Meireles' , 'Fortaleza', 'CE', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(14, '77403-360', 'Praça da Bíblia', 'Jardim Eldorado' , 'Gurupi', 'TO', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(8, '58428-220', 'Avenida Vinte e Sete de Julho', ' Centenário' , 'Campina Grande', 'PB', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(7, '12500-130', 'Rua Castro Alves', 'Centro' , 'Guaratinguetá', 'SP', GETDATE());
INSERT INTO ENDERECO (ID_CLIENTE, CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO) 
VALUES(13, '26195-340', 'Rua Verdade', 'Jardim Ideal' , 'Belford Roxo', 'RJ', GETDATE());


			/* ----------------- CRIANDO A TABELA PRODUTO ----------------- */

CREATE TABLE PRODUTO (
		IDPRODUTO INT PRIMARY KEY IDENTITY,
		DESC_PRODUTO VARCHAR (255) NOT NULL, 
		PRECO DECIMAL (10,2) NOT NULL, 
		DATA_INCLUSAO DATETIME, 
		DATA_ALTERACAO DATETIME, 
		STATUS_PEDIDO VARCHAR (30) CHECK (STATUS_PEDIDO IN ('Não Informado' ,'Pedido Realizado', 'Pedido Recusado')),
		ID_CLIENTE INT

-- CHAVE ESTRANGEIRA

		FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTE(IDCLIENTE)

	);

			/* ----------------- ALGUNS DADOS DA TABELA PRODUTO ----------------- */

INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Lampada', 53.00, 'Não Informado', GETDATE(), 9);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Aspirador de Pó', 531.20, 'Não Informado', GETDATE(), 4);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Smartphone', 1800.00, 'Pedido Recusado', GETDATE(), 8);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Fone', 52.90, 'Pedido Recusado', GETDATE(), 6);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Vassoura', 16.00, 'Pedido Realizado', GETDATE(), 12);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Pilha', 18.70, 'Pedido Recusado', GETDATE(), 15);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Caderno', 12.00, 'Pedido Realizado', GETDATE(), 7);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Mouse', 87.00, 'Não Informado', GETDATE(), 3);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Monitor', 1200.00, 'Não Informado', GETDATE(), 4);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Smart TV', 2400.00, 'Pedido Recusado', GETDATE(), 3);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('WebCam', 250.10, 'Pedido Realizado', GETDATE(), 1);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Notebook', 3200.00, 'Pedido Realizado', GETDATE(), 16);
INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE) 
VALUES('Camiseta HRX', 18.00, 'Pedido Realizado', GETDATE(), 8);


			/* ----------------- PROCEDURES ----------------- */

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON


-- NÃO PERMITIR A INSERT MANUAL NA PROCEDURE

SET IDENTITY_INSERT dbo.CLIENTE ON

-- PERMITIR A INSERT MANUAL NA PROCEDURE

SET IDENTITY_INSERT dbo.cliente OFF;


/* -------------- PROCEDURE CRUD CLIENTE -------------- */


CREATE OR ALTER PROCEDURE CRUD_CLIENTE
	@ACAO INT, -- 1) INCLUIR, 2) APAGAR e 3) ALTERAR
	@IDCLIENTE INT = NULL,
	@NOME VARCHAR (100) = NULL,
	@EMAIL VARCHAR (255) = NULL,
	@SENHA VARCHAR (32) = NULL

AS

BEGIN -- INICIO DA PROCEDURE

				/* VERIFICAR SE JA EXISTE CLIENTE CADASTRADO */

	IF (@ACAO = 1)
		BEGIN
			IF EXISTS (SELECT NOME, EMAIL, SENHA 
					   FROM CLIENTE
					   WHERE EMAIL = @EMAIL)
			   
			SELECT 'USUÁRIO JA EXISTENTE' AS MENSAGEM;
		

				/* INCLUI UM NOVO CLIENTE NA TABELA CLIENTE */

	ELSE
			INSERT INTO CLIENTE (NOME, EMAIL, SENHA, DATA_INCLUSAO)
			VALUES (@NOME, @EMAIL, @SENHA, GETDATE())
		END
				
				/* APAGA O CLIENTE DA TABELA CLIENTE */
		
	ELSE IF (@ACAO = 2)
			BEGIN
				DELETE 
				FROM CLIENTE
				WHERE IDCLIENTE = @IDCLIENTE;
			END
	
	ELSE IF (@ACAO = 3)
			BEGIN
				UPDATE CLIENTE
				SET NOME = @NOME, EMAIL = @EMAIL, SENHA = @SENHA, DATA_ALTERACAO = GETDATE()
				WHERE IDCLIENTE = @IDCLIENTE;
			END
END -- FIM DA PROCEDURE


/* -------------- PROCEDURE CRUD ENDEREÇO -------------- */



CREATE OR ALTER PROCEDURE CRUD_ENDERECO
	@ACAO INT, -- 1) INCLUIR, 2) APAGAR e 3) ALTERAR
	@IDENDERECO INT = NULL,
	@CEP VARCHAR (10),
	@COMPLEMENTO VARCHAR (255),
	@BAIRRO VARCHAR (255),
	@CIDADE VARCHAR (255),
	@ESTADO VARCHAR (2),
	@ID_CLIENTE INT

AS

BEGIN -- INICIO DA PROCEDURE

				/* VERIFICAR SE JA EXISTE CLIENTE CADASTRADO */

	IF (@ACAO = 1)
		BEGIN
			INSERT INTO ENDERECO (CEP, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, DATA_INCLUSAO, ID_CLIENTE)
			VALUES (@CEP, @COMPLEMENTO, @BAIRRO, @CIDADE, @ESTADO, GETDATE(), @ID_CLIENTE)
		END
				
				/* APAGA O CLIENTE DA TABELA CLIENTE */
		
	ELSE IF (@ACAO = 2)
			BEGIN
				DELETE 
				FROM ENDERECO
				WHERE IDENDERECO = @IDENDERECO;
			END
	
	ELSE IF (@ACAO = 3)
			BEGIN
				UPDATE ENDERECO
				SET CEP = @CEP, COMPLEMENTO = @COMPLEMENTO, BAIRRO = @BAIRRO, CIDADE = @CIDADE, ESTADO = @ESTADO, DATA_ALTERACAO = GETDATE()
				WHERE IDENDERECO = @IDENDERECO;
			END
END -- FIM DA PROCEDURE


/* -------------- PROCEDURE CRUD PRODUTO -------------- */

CREATE OR ALTER PROCEDURE CRUD_PRODUTO
	@ACAO INT, -- 1) INCLUIR, 2) APAGAR e 3) ALTERAR
	@IDPRODUTO INT = NULL,
	@DESC_PRODUTO VARCHAR (255),
	@PRECO DECIMAL (10,2),
	@STATUS_PEDIDO VARCHAR (30),
	@ID_CLIENTE INT

AS

BEGIN -- INICIO DA PROCEDURE

				/* VERIFICAR SE JA EXISTE CLIENTE CADASTRADO */

	IF (@ACAO = 1)
		BEGIN
			INSERT INTO PRODUTO (DESC_PRODUTO, PRECO, STATUS_PEDIDO, DATA_INCLUSAO, ID_CLIENTE)
			VALUES (@DESC_PRODUTO, @PRECO, @STATUS_PEDIDO, GETDATE(), @ID_CLIENTE)
		END
				
				/* APAGA O CLIENTE DA TABELA CLIENTE */
		
	ELSE IF (@ACAO = 2)
			BEGIN
				DELETE 
				FROM PRODUTO
				WHERE IDPRODUTO = @IDPRODUTO;
			END
	
	ELSE IF (@ACAO = 3)
			BEGIN
				UPDATE PRODUTO
				SET DESC_PRODUTO = @DESC_PRODUTO, PRECO = @PRECO, STATUS_PEDIDO = @STATUS_PEDIDO, DATA_ALTERACAO = GETDATE()
				WHERE IDPRODUTO = @IDPRODUTO;
			END
END -- FIM DA PROCEDURE


/*

-- DROP PROCEDURE CRUD_CLIENTE;
-- DROP PROCEDURE CRUD_ENDERECO;

*/

/*

DROP TABLE dbo.ENDERECO;
DROP TABLE dbo.PRODUTO;
DROP TABLE dbo.CLIENTE;

*/

/*

SELECT * FROM PRODUTO;

SELECT C.IDCLIENTE, C.NOME, P.DESC_PRODUTO, P.PRECO, P.DATA_INCLUSAO, P.DATA_ALTERACAO
FROM CLIENTE C
INNER JOIN PRODUTO P
ON IDCLIENTE = ID_CLIENTE;

*/

/*

SELECT * FROM ENDERECO;

SELECT C.IDCLIENTE, C.NOME, E.CEP, E.CIDADE, E.ESTADO, E.ID_CLIENTE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON IDCLIENTE = ID_CLIENTE;

*/

/*

EXEC CRUD_CLIENTE @ACAO = 1, @IDCLIENTE = NULL, @NOME = 'Milena Nunes da Silva', @EMAIL = 'milena651@gmail.com', @SENHA = '5aF@s5@%F{F64!';
EXEC CRUD_CLIENTE @ACAO = 1, @IDCLIENTE = NULL, @NOME = 'Marina Araujo Ferreira', @EMAIL = 'marin_araujo79@outlook.com', @SENHA = 'i$)5F)}mm*q;N>'; 
EXEC CRUD_CLIENTE @ACAO = 2, @IDCLIENTE = 18;
EXEC CRUD_CLIENTE @ACAO = 3, @IDCLIENTE = 17, @NOME = 'Milena Nunes', @EMAIL = 'milena61@gmail.com', @SENHA = 'Fb;uRkm-B3y^MM>I?';


EXEC CRUD_ENDERECO @ACAO = 1, @IDENDERECO = NULL, @CEP = '08370-430', @COMPLEMENTO = 'Avenida Caboré', @BAIRRO = 'Jardim Maria Lídia', @CIDADE = 'São Paulo', @ESTADO = 'SP', @ID_CLIENTE = 5;
EXEC CRUD_ENDERECO @ACAO = 2, @IDENDERECO = 25, @CEP = '08370-430', @COMPLEMENTO = 'Avenida Caboré', @BAIRRO = 'Jd. Maria Lídia', @CIDADE = 'São Paulo', @ESTADO = 'SP', @ID_CLIENTE = 5;
EXEC CRUD_ENDERECO @ACAO = 3, @IDENDERECO = 25, @CEP = '08370-430', @COMPLEMENTO = 'Avenida Caboré', @BAIRRO = 'Jd. Maria Lídia', @CIDADE = 'São Paulo', @ESTADO = 'SP', @ID_CLIENTE = 5;


EXEC CRUD_PRODUTO @ACAO = 1, @IDPRODUTO = NULL, @DESC_PRODUTO = 'Gabinete', @PRECO = '382.00', @STATUS_PEDIDO = 'Pedido Realizado', @ID_CLIENTE = 7;
EXEC CRUD_PRODUTO @ACAO = 3, @IDPRODUTO = 18, @DESC_PRODUTO = 'Gabinete', @PRECO = '352.00', @STATUS_PEDIDO = 'Pedido Recusado', @ID_CLIENTE = 7;
EXEC CRUD_PRODUTO @ACAO = 2, @IDPRODUTO = 18, @DESC_PRODUTO = 'Gabinete', @PRECO = '352.00', @STATUS_PEDIDO = 'Pedido Recusado', @ID_CLIENTE = 7;


*/